from aiogram_dialog import Dialog, StartMode, Window
from aiogram_dialog.widgets.input import MessageInput
from magic_filter import F

from src.core.enums import BannerName, Currency
from src.telegram.states import DashboardRemnashop, RemnashopExtra
from src.telegram.widgets import Banner, I18nFormat, IgnoreUpdate
from src.telegram.widgets.kbd import Button, Row, Start, SwitchTo

from .getters import device_purchase_price_getter, extra_getter
from .handlers import (
    on_cooldown_input,
    on_device_purchase_currency_select,
    on_device_purchase_price_input,
    on_device_purchase_toggle,
    on_mini_app_reserve_toggle,
    on_toggle,
    on_trial_channel_guard_toggle,
)

main = Window(
    Banner(BannerName.DASHBOARD),
    I18nFormat("msg-extra-main"),
    Row(
        SwitchTo(
            text=I18nFormat(
                "btn-remnashop-extra.device-single",
                enabled=F["device_single_enabled"],
            ),
            id="device_single",
            state=RemnashopExtra.DEVICE_SINGLE,
        ),
    ),
    Row(
        SwitchTo(
            text=I18nFormat(
                "btn-remnashop-extra.device-all",
                enabled=F["device_all_enabled"],
            ),
            id="device_all",
            state=RemnashopExtra.DEVICE_ALL,
        ),
    ),
    Row(
        SwitchTo(
            text=I18nFormat(
                "btn-remnashop-extra.link-reset",
                enabled=F["link_reset_enabled"],
            ),
            id="link_reset",
            state=RemnashopExtra.LINK_RESET,
        ),
    ),
    Row(
        SwitchTo(
            text=I18nFormat(
                "btn-remnashop-extra.referral-reset",
                enabled=F["referral_reset_enabled"],
            ),
            id="referral_reset",
            state=RemnashopExtra.REFERRAL_RESET,
        ),
    ),
    Row(
        SwitchTo(
            text=I18nFormat(
                "btn-remnashop-extra.trial-channel-guard",
                enabled=F["trial_channel_guard_enabled"],
            ),
            id="trial_channel_guard",
            state=RemnashopExtra.TRIAL_CHANNEL_GUARD,
        ),
    ),
    Row(
        SwitchTo(
            text=I18nFormat(
                "btn-remnashop-extra.mini-app-reserve",
                enabled=F["mini_app_reserve_enabled"],
            ),
            id="mini_app_reserve",
            state=RemnashopExtra.MINI_APP_RESERVE,
        ),
    ),
    Row(
        SwitchTo(
            text=I18nFormat(
                "btn-remnashop-extra.device-purchase",
                enabled=F["device_purchase_enabled"],
            ),
            id="device_purchase",
            state=RemnashopExtra.DEVICE_PURCHASE,
        ),
    ),
    Row(
        Start(
            text=I18nFormat("btn-back.general"),
            id="back",
            state=DashboardRemnashop.MAIN,
            mode=StartMode.RESET_STACK,
        ),
    ),
    IgnoreUpdate(),
    state=RemnashopExtra.MAIN,
    getter=extra_getter,
)

device_single = Window(
    Banner(BannerName.DASHBOARD),
    I18nFormat(
        "msg-extra-device-single",
        enabled=F["device_single_enabled"],
        cooldown=F["device_single_cooldown"],
    ),
    Row(
        Button(
            text=I18nFormat("btn-remnashop-extra.toggle", enabled=F["device_single_enabled"]),
            id="device_single_toggle",
            on_click=on_toggle,
        ),
    ),
    Row(
        SwitchTo(
            text=I18nFormat("btn-back.general"),
            id="back",
            state=RemnashopExtra.MAIN,
        ),
    ),
    MessageInput(func=on_cooldown_input),
    IgnoreUpdate(),
    state=RemnashopExtra.DEVICE_SINGLE,
    getter=extra_getter,
)

device_all = Window(
    Banner(BannerName.DASHBOARD),
    I18nFormat(
        "msg-extra-device-all",
        enabled=F["device_all_enabled"],
        cooldown=F["device_all_cooldown"],
    ),
    Row(
        Button(
            text=I18nFormat("btn-remnashop-extra.toggle", enabled=F["device_all_enabled"]),
            id="device_all_toggle",
            on_click=on_toggle,
        ),
    ),
    Row(
        SwitchTo(
            text=I18nFormat("btn-back.general"),
            id="back",
            state=RemnashopExtra.MAIN,
        ),
    ),
    MessageInput(func=on_cooldown_input),
    IgnoreUpdate(),
    state=RemnashopExtra.DEVICE_ALL,
    getter=extra_getter,
)

link_reset = Window(
    Banner(BannerName.DASHBOARD),
    I18nFormat(
        "msg-extra-link-reset",
        enabled=F["link_reset_enabled"],
        cooldown=F["link_reset_cooldown"],
    ),
    Row(
        Button(
            text=I18nFormat("btn-remnashop-extra.toggle", enabled=F["link_reset_enabled"]),
            id="link_toggle",
            on_click=on_toggle,
        ),
    ),
    Row(
        SwitchTo(
            text=I18nFormat("btn-back.general"),
            id="back",
            state=RemnashopExtra.MAIN,
        ),
    ),
    MessageInput(func=on_cooldown_input),
    IgnoreUpdate(),
    state=RemnashopExtra.LINK_RESET,
    getter=extra_getter,
)

referral_reset = Window(
    Banner(BannerName.DASHBOARD),
    I18nFormat(
        "msg-extra-referral-reset",
        enabled=F["referral_reset_enabled"],
        cooldown=F["referral_reset_cooldown"],
    ),
    Row(
        Button(
            text=I18nFormat("btn-remnashop-extra.toggle", enabled=F["referral_reset_enabled"]),
            id="referral_toggle",
            on_click=on_toggle,
        ),
    ),
    Row(
        SwitchTo(
            text=I18nFormat("btn-back.general"),
            id="back",
            state=RemnashopExtra.MAIN,
        ),
    ),
    MessageInput(func=on_cooldown_input),
    IgnoreUpdate(),
    state=RemnashopExtra.REFERRAL_RESET,
    getter=extra_getter,
)

trial_channel_guard = Window(
    Banner(BannerName.DASHBOARD),
    I18nFormat(
        "msg-extra-trial-channel-guard",
        enabled=F["trial_channel_guard_enabled"],
    ),
    Row(
        Button(
            text=I18nFormat(
                "btn-remnashop-extra.toggle",
                enabled=F["trial_channel_guard_enabled"],
            ),
            id="trial_channel_guard_toggle",
            on_click=on_trial_channel_guard_toggle,
        ),
    ),
    Row(
        SwitchTo(
            text=I18nFormat("btn-back.general"),
            id="back",
            state=RemnashopExtra.MAIN,
        ),
    ),
    IgnoreUpdate(),
    state=RemnashopExtra.TRIAL_CHANNEL_GUARD,
    getter=extra_getter,
)

mini_app_reserve = Window(
    Banner(BannerName.DASHBOARD),
    I18nFormat(
        "msg-extra-mini-app-reserve",
        enabled=F["mini_app_reserve_enabled"],
    ),
    Row(
        Button(
            text=I18nFormat(
                "btn-remnashop-extra.toggle",
                enabled=F["mini_app_reserve_enabled"],
            ),
            id="mini_app_reserve_toggle",
            on_click=on_mini_app_reserve_toggle,
        ),
    ),
    Row(
        SwitchTo(
            text=I18nFormat("btn-back.general"),
            id="back",
            state=RemnashopExtra.MAIN,
        ),
    ),
    IgnoreUpdate(),
    state=RemnashopExtra.MINI_APP_RESERVE,
    getter=extra_getter,
)

device_purchase = Window(
    Banner(BannerName.DASHBOARD),
    I18nFormat(
        "msg-extra-device-purchase",
        enabled=F["device_purchase_enabled"],
        price_xtr=F["device_purchase_price_xtr"],
        price_rub=F["device_purchase_price_rub"],
        price_usd=F["device_purchase_price_usd"],
    ),
    Row(
        Button(
            text=I18nFormat(
                "btn-remnashop-extra.toggle",
                enabled=F["device_purchase_enabled"],
            ),
            id="device_purchase_toggle",
            on_click=on_device_purchase_toggle,
        ),
    ),
    Row(
        Button(
            text=I18nFormat(
                "btn-remnashop-extra.device-price",
                currency=Currency.XTR.value,
                symbol=Currency.XTR.symbol,
                price=F["device_purchase_price_xtr"],
            ),
            id="device_price_xtr",
            on_click=on_device_purchase_currency_select,
        ),
        Button(
            text=I18nFormat(
                "btn-remnashop-extra.device-price",
                currency=Currency.RUB.value,
                symbol=Currency.RUB.symbol,
                price=F["device_purchase_price_rub"],
            ),
            id="device_price_rub",
            on_click=on_device_purchase_currency_select,
        ),
        Button(
            text=I18nFormat(
                "btn-remnashop-extra.device-price",
                currency=Currency.USD.value,
                symbol=Currency.USD.symbol,
                price=F["device_purchase_price_usd"],
            ),
            id="device_price_usd",
            on_click=on_device_purchase_currency_select,
        ),
    ),
    Row(
        SwitchTo(
            text=I18nFormat("btn-back.general"),
            id="back",
            state=RemnashopExtra.MAIN,
        ),
    ),
    IgnoreUpdate(),
    state=RemnashopExtra.DEVICE_PURCHASE,
    getter=extra_getter,
)

device_purchase_price = Window(
    Banner(BannerName.DASHBOARD),
    I18nFormat(
        "msg-extra-device-purchase-price",
        currency=F["device_currency"],
        symbol=F["device_currency_symbol"],
        price=F["device_price"],
    ),
    MessageInput(func=on_device_purchase_price_input),
    Row(
        SwitchTo(
            text=I18nFormat("btn-back.general"),
            id="back",
            state=RemnashopExtra.DEVICE_PURCHASE,
        ),
    ),
    IgnoreUpdate(),
    state=RemnashopExtra.DEVICE_PURCHASE_PRICE,
    getter=device_purchase_price_getter,
)

router = Dialog(
    main,
    device_single,
    device_all,
    link_reset,
    referral_reset,
    trial_channel_guard,
    mini_app_reserve,
    device_purchase,
    device_purchase_price,
)
